import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { PropsWithChildren } from "react";
import { Header } from "@/ui/components/Header";

const lato = Lato({ subsets: ["latin"], weight: ["100", "300", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={`${lato.className} bg-neutral-200`}>
        <main className={"min-h-screen w-full"}>
          <Header />
          <main className={"py-4"}>{children}</main>
        </main>
      </body>
    </html>
  );
}
